root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["make templ"]
cmd = "go build -o ./tmp/main ./cmd/majin"
bin = "tmp/main"
full_bin = "APP_ENV=development ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
exclude_dir = ["assets", "tmp", "vendor", "static", "node_modules"]
exclude_regex = [".*_templ.go"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"
send_interrupt = false

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
